#!/usr/bin/env python3
"""Home Network Monitor - tiny LAN web server for the dashboard.

Lets everyone on your home network open the dashboard from any device:

    http://<this-machine's-ip>:8080/

The LAN sees ONLY dashboard.html and the two vendored chart libraries -
the database, logs, and config files are not reachable from the network.
The setup wizard (/setup) and settings pages (/settings), plus the
/api/* endpoints that read and write the config files, answer ONLY to
this machine itself (127.0.0.1); other devices get a polite 403.

Stdlib only; runs on Windows, macOS, and Linux. On Windows, setup.ps1
registers it as the "NetMon Web" scheduled task and opens TCP 8080 on
the Private firewall profile. Change the port with the NETMON_WEB_PORT
environment variable if 8080 is taken.
"""
import ipaddress
import json
import os
import sys
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

try:
    from version import __version__
except ImportError:  # partially-copied install
    __version__ = "0.0.0"

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PORT = int(os.environ.get("NETMON_WEB_PORT", "8080"))

# Under pythonw.exe (no console) stdout/stderr are None - send them to logs/
# like monitor.py does, so crashes are visible somewhere.
if sys.stdout is None or sys.stderr is None:
    _log_dir = os.path.join(BASE_DIR, "logs")
    os.makedirs(_log_dir, exist_ok=True)
    if sys.stdout is None:
        sys.stdout = open(os.path.join(_log_dir, "web.out.log"), "a", buffering=1, encoding="utf-8")
    if sys.stderr is None:
        sys.stderr = open(os.path.join(_log_dir, "web.err.log"), "a", buffering=1, encoding="utf-8")

# The settings/wizard layer is optional: a partially-copied install without
# these modules still serves the dashboard fine.
try:
    import settings_api
    import settings_page
except ImportError:
    settings_api = settings_page = None

# LAN whitelist: URL path -> (file on disk, content type). Anything else is
# a 404 for LAN clients - this list is the entire attack surface exposed to
# the network.
ROUTES = {
    "/": (os.path.join(BASE_DIR, "dashboard.html"), "text/html; charset=utf-8"),
    "/dashboard.html": (os.path.join(BASE_DIR, "dashboard.html"), "text/html; charset=utf-8"),
    # printable ISP evidence report — same data the dashboard already
    # exposes to the LAN, pre-generated by dashboard.py
    "/report.html": (os.path.join(BASE_DIR, "report.html"), "text/html; charset=utf-8"),
    "/vendor/chart.umd.min.js": (
        os.path.join(BASE_DIR, "vendor", "chart.umd.min.js"),
        "application/javascript; charset=utf-8"),
    "/vendor/chartjs-adapter-date-fns.bundle.min.js": (
        os.path.join(BASE_DIR, "vendor", "chartjs-adapter-date-fns.bundle.min.js"),
        "application/javascript; charset=utf-8"),
}

MAX_POST_BYTES = 256 * 1024

# The ONLY /api/* paths reachable from the LAN (exact match). Everything
# else under /api/* stays localhost-only. "Test now" is deliberately
# LAN-usable: "internet feels slow on my phone -> tap Test" is its whole
# point, it takes no meaningful input, and it's rate-limited server-side.
# Delete an entry here to make it localhost-only again.
LAN_API = {
    "GET": {"/api/test/status"},
    "POST": {"/api/test/run"},
}

WARMING_UP_HTML = """<!DOCTYPE html><html><head><meta charset="UTF-8">
<title>Home Network Monitor</title></head>
<body style="font-family:sans-serif;background:#05080f;color:#e8eef8;
display:flex;align-items:center;justify-content:center;height:100vh;margin:0">
<div style="max-width:420px;text-align:center"><h2>Warming up&hellip;</h2>
<p style="color:#a2b3cb">The dashboard is generated every minute and the first one
isn't ready yet. This page retries automatically.</p></div></body></html>"""

LOCAL_ONLY_HTML = """<!DOCTYPE html><html><head><meta charset="UTF-8">
<title>Settings unavailable</title></head>
<body style="font-family:sans-serif;background:#05080f;color:#e8eef8;
display:flex;align-items:center;justify-content:center;height:100vh;margin:0">
<div style="max-width:420px;text-align:center"><h2>Settings live on the monitor PC</h2>
<p style="color:#a2b3cb">For safety, configuration can only be changed on the computer
running the monitor. On that machine, open<br>
<code style="color:#3fc6ff">http://localhost:%d%s</code></p>
<p><a href="/" style="color:#3fc6ff">Back to the dashboard</a></p></div></body></html>"""


class DashboardHandler(BaseHTTPRequestHandler):
    server_version = "NetMonWeb/" + __version__

    # ---- helpers ---------------------------------------------------------

    def _is_local(self):
        return self.client_address[0] in ("127.0.0.1", "::1")

    def _host_is_local(self):
        """Anti-DNS-rebinding: a browser was told to talk to 'localhost',
        so a request whose Host header names some other site was made by a
        page from that other site."""
        host = (self.headers.get("Host") or "").split(":", 1)[0].strip("[]").lower()
        return host in ("localhost", "127.0.0.1", "::1")

    def _host_is_private_ip(self):
        """The LAN-API variant of the rebinding check: LAN users browse the
        dashboard by IP, so for the carved-out endpoints we accept a Host
        header that is a private/loopback IP LITERAL. A hostname Host
        header still means some website's DNS pointed here — reject."""
        if self._host_is_local():
            return True
        host = (self.headers.get("Host") or "").split(":", 1)[0].strip("[]")
        try:
            return ipaddress.ip_address(host).is_private
        except ValueError:
            return False

    def _send(self, status, body, ctype="text/html; charset=utf-8", extra=None):
        data = body.encode("utf-8") if isinstance(body, str) else body
        self.send_response(status)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(data)))
        self.send_header("Cache-Control", "no-store")
        for k, v in (extra or {}).items():
            self.send_header(k, v)
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(data)

    def _send_json(self, status, payload):
        self._send(status, json.dumps(payload), "application/json; charset=utf-8")

    # ---- LAN whitelist (unchanged behavior) ------------------------------

    def _serve(self, send_body):
        path = self.path.split("?", 1)[0].split("#", 1)[0]

        # Localhost-only surface: wizard, settings, and their API.
        if settings_api and path in ("/settings", "/setup") :
            if not self._is_local():
                self._send(403, LOCAL_ONLY_HTML % (PORT, path))
                return
            self._send(200, settings_page.SETTINGS_HTML if path == "/settings"
                       else settings_page.WIZARD_HTML)
            return
        if settings_api and path.startswith("/api/"):
            lan_ok = path in LAN_API["GET"] and self._host_is_private_ip()
            if not self._is_local() and not lan_ok:
                self._send_json(403, {"ok": False, "error": "settings are only available on the monitor PC"})
                return
            try:
                status, payload = settings_api.handle_get(path)
            except Exception as e:
                status, payload = 500, {"ok": False, "error": f"{type(e).__name__}: {e}"}
            self._send_json(status, payload)
            return
        # Fresh install, browsed from the machine itself: walk them into
        # the wizard instead of showing an empty dashboard.
        if settings_api and path == "/" and self._is_local() and settings_api.wizard_needed():
            self._send(302, "", extra={"Location": "/setup"})
            return

        route = ROUTES.get(path)
        if route is None:
            self.send_response(404)
            self.send_header("Content-Length", "0")
            self.end_headers()
            return
        if not os.path.exists(route[0]):
            if path in ("/", "/dashboard.html"):
                # Fresh install: dashboard.py hasn't produced its first file
                # yet (runs every minute) - hold the door open instead of 404ing.
                self._send(200, WARMING_UP_HTML, extra={"Refresh": "10"})
            else:
                self.send_response(404)
                self.send_header("Content-Length", "0")
                self.end_headers()
            return
        file_path, ctype = route
        try:
            with open(file_path, "rb") as f:
                body = f.read()
        except OSError:
            # dashboard.py may be rewriting the file right now - retry shortly
            self.send_response(503)
            self.send_header("Retry-After", "2")
            self.send_header("Content-Length", "0")
            self.end_headers()
            return
        self.send_response(200)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        if ctype.startswith("text/html"):
            # always re-fetch the page so the 60s auto-refresh sees new data
            self.send_header("Cache-Control", "no-store")
        else:
            self.send_header("Cache-Control", "public, max-age=86400")
        self.end_headers()
        if send_body:
            self.wfile.write(body)

    def do_GET(self):
        self._serve(True)

    def do_HEAD(self):
        self._serve(False)

    # ---- localhost-only writes -------------------------------------------

    def do_POST(self):
        path = self.path.split("?", 1)[0].split("#", 1)[0]
        if settings_api is None or not path.startswith("/api/"):
            self._send_json(404, {"ok": False, "error": "unknown endpoint"})
            return
        # There is deliberately no password on the settings API, so these
        # guards do the work instead: only the machine itself may connect,
        # and a browser page from some random website must not be able to
        # ride along on that (CSRF / DNS rebinding). The LAN_API paths get
        # a deliberate carve-out: any LAN client, but the Host header must
        # be a private-IP literal (and the JSON Content-Type below forces a
        # CORS preflight this server never answers, killing cross-site
        # fetches from the internet).
        lan_ok = path in LAN_API["POST"] and self._host_is_private_ip()
        if not lan_ok and (not self._is_local() or not self._host_is_local()):
            self._send_json(403, {"ok": False, "error": "settings are only available on the monitor PC"})
            return
        origin = self.headers.get("Origin")
        if origin:
            origin_host = origin.split("//", 1)[-1].split(":", 1)[0].strip("[]").lower()
            origin_ok = origin_host in ("localhost", "127.0.0.1")
            if not origin_ok and lan_ok:
                # LAN carve-out: same-origin fetches from the dashboard page
                # carry the dashboard's own private-IP origin
                try:
                    origin_ok = ipaddress.ip_address(origin_host).is_private
                except ValueError:
                    origin_ok = False
            if not origin_ok:
                self._send_json(403, {"ok": False, "error": "cross-origin requests are not allowed"})
                return
        ctype = (self.headers.get("Content-Type") or "").split(";", 1)[0].strip().lower()
        if ctype != "application/json":
            self._send_json(415, {"ok": False, "error": "Content-Type must be application/json"})
            return
        try:
            length = int(self.headers.get("Content-Length") or 0)
        except ValueError:
            length = -1
        if length < 0 or length > MAX_POST_BYTES:
            self._send_json(413, {"ok": False, "error": "request body too large"})
            return
        try:
            body = json.loads(self.rfile.read(length).decode("utf-8") or "{}")
        except (ValueError, UnicodeDecodeError):
            self._send_json(400, {"ok": False, "error": "body is not valid JSON"})
            return
        try:
            status, payload = settings_api.handle_post(path, body)
        except Exception as e:
            # a handler bug must not kill the whole pythonw service
            status, payload = 500, {"ok": False, "error": f"{type(e).__name__}: {e}"}
        self._send_json(status, payload)

    def log_message(self, fmt, *args):
        pass  # quiet - no per-request log spam


def main():
    server = ThreadingHTTPServer(("0.0.0.0", PORT), DashboardHandler)
    print(f"serving the dashboard on port {PORT} (all interfaces)")
    server.serve_forever()


if __name__ == "__main__":
    if "--version" in sys.argv:
        print(__version__)
        sys.exit(0)
    main()
